server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.94.139/test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  typeaAliasesPackage: com.example.test.bean

swagger:
  enabled: true
  title: test-API
  description: API文档
  base-package:  com.example.test.controller
  base-path: /**
  exclude-path: /error